version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      development-tooling:
        dependency-type: development
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      codeql:
        patterns:
          - github/codeql-action/*
    open-pull-requests-limit: 3
